# mysite.conf

upstream mysite_backend {
    server 127.0.0.1:32768;
    server 127.0.0.1:32769;
    server 127.0.0.1:32770;
    server 127.0.0.1:32771;
}

server {
    listen 80;
    server_name mysite.example.com;

    location / {
        proxy_pass http://mysite_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
